### PR TITLE
Fix cpp client examples and use g++ build project

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

Fix cpp client examples and use g++ build project

### CODE REVIEW

**Comment by sijie** [comment]
What is the motivation of switching CMake to g++?

**Comment by wolfstudy** [comment]
> What is the motivation of switching CMake to g++?

Currently, this build process works locally, CMake has not been successfully debugged yet.

**Comment by wolfstudy** [comment]
After that, we should use CMake to build this project and will track this task in #23

**Comment by sijie** [comment]
@wolfstudy noted with thanks.

**Pull request merged**
